# Generated by Django 5.0.6 on 2024-06-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="photo",
            field=models.ImageField(upload_to="media/review_photos/"),
        ),
    ]
