# Generated by Django 5.0.6 on 2024-07-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_review_favorited_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="favorited_by",
        ),
        migrations.AddField(
            model_name="profile",
            name="favorite_reviews",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by_profiles", to="core.review"
            ),
        ),
    ]
