# Generated by Django 5.0.6 on 2024-07-06 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_review_favorited_by_profile_favorite_reviews"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "permissions": [
                    ("mark_featured_review", "Can mark a review as featured")
                ]
            },
        ),
    ]
