# Generated by Django 5.0.6 on 2024-07-07 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_review_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={},
        ),
    ]
